name: 'Load .env'
description: 'Loads variables from .env file'

outputs:
  image-id-base:
    description: 'Base image id'
    value: ${{ steps.loadenv.outputs.IMAGE_ID_BASE }}

runs:
  using: "composite"
  steps:
    - name: Load .env
      id: loadenv
      run: |
        set -o allexport; source .env; set +o allexport
        echo "IMAGE_ID_BASE=$IMAGE_ID_BASE" >> $GITHUB_OUTPUT
      shell: bash