name: 'Load .env'
description: 'Loads variables from .env file'

outputs:
  image-tag:
    description: 'Base image id'
    value: ${{ steps.loadenv.outputs.IMAGE_TAG }}

runs:
  using: "composite"
  steps:
    - name: Load .env
      id: loadenv
      run: |
        set -o allexport; source .env; set +o allexport
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
      shell: bash