version: '3.7'

services:

  neo-consensus:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.neo-node-with-plugins
      target: NeoCliFinal
      args:
        IMAGE_TAG: ${IMAGE_TAG}
    image: ghcr.io/axlabs/neo3-privatenet-docker/neo-cli-with-plugins:${IMAGE_TAG}
    hostname: neo-consensus
    container_name: neo-consensus
    volumes:
      - ./config/config-consensus.privatenet3.json:/neo-cli/config.json:ro
      - ./config/wallet-consensus.privatenet3.json:/neo-cli/wallet.json:rw
      - ./config/rpcserver.config-consensus.json:/neo-cli/Plugins/RpcServer/RpcServer.json:ro
      - ./config/dbft.config-consensus.json:/neo-cli/Plugins/DBFTPlugin/DBFTPlugin.json:ro
      - ./config/applicationlogs.config-consensus.json:/neo-cli/Plugins/ApplicationLogs/ApplicationLogs.json:ro
      - ./config/oracle.config-consensus.json:/neo-cli/Plugins/OracleService/OracleService.json:ro
      - ./config/tokentracker.config-consensus.json:/neo-cli/Plugins/TokensTracker/TokensTracker.json:ro
      - ./config/stateservice.config-consensus.json:/neo-cli/Plugins/StateService/StateService.json:ro
      - ./config/storagedumper.config-consensus.json:/neo-cli/Plugins/StorageDumper/StorageDumper.json:ro
    ports:
      - "40332:40332"

  neo-client1:
    image: ghcr.io/axlabs/neo3-privatenet-docker/neo-cli-with-plugins:${IMAGE_TAG}
    hostname: neo-client1
    container_name: neo-client1
    depends_on:
      - neo-consensus
    volumes:
      - ./config/config-client1.privatenet3.json:/neo-cli/config.json:ro
      - ./config/wallet-client1.privatenet3.json:/neo-cli/wallet.json:rw
      - ./config/rpcserver.config-client1.json:/neo-cli/Plugins/RpcServer/RpcServer.json:ro
      - ./config/applicationlogs.config-client1.json:/neo-cli/Plugins/ApplicationLogs/ApplicationLogs.json:ro
      - ./config/oracle.config-client1.json:/neo-cli/Plugins/OracleService/OracleService.json:ro
      - ./config/tokentracker.config-client1.json:/neo-cli/Plugins/TokensTracker/TokensTracker.json:ro
      - ./config/stateservice.config-client1.json:/neo-cli/Plugins/StateService/StateService.json:ro
      - ./config/storagedumper.config-client1.json:/neo-cli/Plugins/StorageDumper/StorageDumper.json:ro
    ports:
      - "10332:10332"

  neo-client2:
    image: ghcr.io/axlabs/neo3-privatenet-docker/neo-cli-with-plugins:${IMAGE_TAG}
    hostname: neo-client2
    container_name: neo-client2
    depends_on:
      - neo-consensus
    volumes:
      - ./config/config-client2.privatenet3.json:/neo-cli/config.json:ro
      - ./config/wallet-client2.privatenet3.json:/neo-cli/wallet.json:rw
      - ./config/rpcserver.config-client2.json:/neo-cli/Plugins/RpcServer/RpcServer.json:ro
      - ./config/applicationlogs.config-client2.json:/neo-cli/Plugins/ApplicationLogs/ApplicationLogs.json:ro
      - ./config/oracle.config-client2.json:/neo-cli/Plugins/OracleService/OracleService.json:ro
      - ./config/tokentracker.config-client2.json:/neo-cli/Plugins/TokensTracker/TokensTracker.json:ro
      - ./config/stateservice.config-client2.json:/neo-cli/Plugins/StateService/StateService.json:ro
      - ./config/storagedumper.config-client2.json:/neo-cli/Plugins/StorageDumper/StorageDumper.json:ro
    ports:
      - "20332:20332"

  neo-go-cli:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.neo-go-with-tools
      args:
        NEO_GO_VERSION: ${NEO_GO_VERSION}
    hostname: neo-go-cli
    container_name: neo-go-cli
    environment:
      - WALLET_PASSWORD=neo
    volumes:
      - ./config/wallet-consensus.privatenet3.json:/wallet.json:ro
      - ./scripts/wait_and_invoke.sh:/wait_and_invoke.sh:ro
    entrypoint: ["sh", "/wait_and_invoke.sh"]