###
# Get the latest block index of `neo-consensus` node:
###

POST http://127.0.0.1:40332 HTTP/1.1
content-type: application/json

{
    "jsonrpc":"2.0",
    "method":"getblockcount",
    "params":[],
    "id":1
}

###
# Open the wallet from the `neo-consensus` node
###

POST http://127.0.0.1:40332 HTTP/1.1
content-type: application/json

{
    "jsonrpc":"2.0",
    "method":"openwallet",
    "params":["wallet.json","neo"],
    "id":1
}

###
# List the addresses in `neo-consensus` wallet:
###

POST http://127.0.0.1:40332 HTTP/1.1
content-type: application/json

{
    "jsonrpc":"2.0",
    "method":"listaddress",
    "params":[],
    "id":1
}

###
# Get all NEP-17 balance of `neo-consensus`' 
# address `NKvR5WeczCQMcVWQD9aaMqegfEoCBXGWpW`, specifically:
###

POST http://127.0.0.1:40332 HTTP/1.1
content-type: application/json

{
    "jsonrpc":"2.0",
    "method":"getnep17balances",
    "params":["NXXazKH39yNFWWZF5MJ8tEN98VYHwzn7g3"],
    "id":1
}

###
# Send 100 NEO from `neo-consensus`' address `NXXazKH39yNFWWZF5MJ8tEN98VYHwzn7g3` 
# to `neo-client1`'s address `NdihqSLYTf1B1WYuzhM52MNqvCNPJKLZaz`
###

POST http://127.0.0.1:40332 HTTP/1.1
content-type: application/json

{
    "jsonrpc":"2.0",
    "method":"sendfrom",
    "params":[
        "0xef4073a0f2b305a38ec4050e4d3d28bc40ea63f5",
        "NXXazKH39yNFWWZF5MJ8tEN98VYHwzn7g3",
        "NdihqSLYTf1B1WYuzhM52MNqvCNPJKLZaz",
        100
    ],
    "id":1
}

###
# Open the wallet of the `neo-client1` 
# through JSON-RPC (**only for test purposes!**):
###

POST http://127.0.0.1:10332 HTTP/1.1
content-type: application/json

{
    "jsonrpc":"2.0",
    "method":"openwallet",
    "params":["wallet.json","neo"],
    "id":1
}

###
# Get all NEP-17 balance of `neo-client1`' address `NdihqSLYTf1B1WYuzhM52MNqvCNPJKLZaz`
# (wait 15 seconds before executing the command, due to the block generation interval):
###

POST http://127.0.0.1:10332 HTTP/1.1
content-type: application/json

{
    "jsonrpc":"2.0",
    "method":"getnep17balances",
    "params":["NdihqSLYTf1B1WYuzhM52MNqvCNPJKLZaz"],
    "id":1
}