# Build the plugins
FROM mcr.microsoft.com/dotnet/sdk:7.0-jammy AS PluginBuild

COPY ./neo-modules /neo-modules
WORKDIR /neo-modules

# If any plugin should be excluded from the build, just set 
# to a regex including the names of dirs.
# Example:
#   REGEX_EXCLUDE_PLUGINS=".*(SystemLog|RpcNep5Tracker)"
ARG REGEX_EXCLUDE_PLUGINS=".*(SystemLog|RpcNep5Tracker|RocksDBStore)"

#
# Some magic here. Time for the kids to leave. Adults only.
#
# The following disgusting shell command is due to the lack of tooling 
# to exclude tests and specific sub-projects in dotnet. *facepalm*
#
# The good side: main artifacts and tests are not mixed up in the 
# same plugins directory, avoiding potential conflicts of .dll versions 
# and other nasty problems. *smile*
#
RUN mkdir -p /plugins && \
	find ./src/ \
		-regextype posix-extended \
		-maxdepth 1 \
		-mindepth 1 \
		-type d \
		-and -not -name '.*' \
		-and -not -regex "${REGEX_EXCLUDE_PLUGINS}" -print0 \
	| xargs -0 -L1 sh -c 'basename $0' \
	| sed 's/ //g' \
	| xargs -I {} sh -c 'echo {} && dotnet publish ./src/{} -c Release /p:ErrorOnDuplicatePublishOutputFiles=false -o /plugins && mkdir -p /plugins/{} && cp /plugins/{}.* /plugins/{}/ && if [ -e ./src/{}/config.json ]; then cp ./src/{}/config.json /plugins/{}/config.json; fi'

# Build the neo-cli
FROM mcr.microsoft.com/dotnet/sdk:7.0-jammy AS NeoCliBuild

COPY ./neo-node/neo-cli /neo-cli
COPY ./neo-node/Neo.ConsoleService /Neo.ConsoleService
COPY ./neo-node/NuGet.Config /neo-cli

WORKDIR /neo-cli
RUN dotnet restore && dotnet publish -c Release -o /app

# Final image: neo-node-with-plugins :-)
FROM mcr.microsoft.com/dotnet/sdk:7.0-jammy AS NeoCliFinal

LABEL org.opencontainers.image.source https://github.com/axlabs/neo3-privatenet-docker

RUN apt-get -y update && \
	apt-get -y install jq nano procps screen libleveldb-dev sqlite3 && \
	rm -rf /var/lib/apt/lists/*

WORKDIR /neo-cli

COPY --from=NeoCliBuild /app .
COPY --from=PluginBuild /plugins ./Plugins

ENTRYPOINT ["screen","-DmS","node","dotnet","neo-cli.dll","-r"]